// <auto-generated />
using System;
using BookWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authors")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookWebApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors", "authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Автор 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Автор 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Автор 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Автор 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Автор 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Автор 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Автор 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Автор 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Автор 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Автор 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Автор 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Автор 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Автор 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Автор 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Автор 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Автор 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Автор 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Автор 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Автор 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Автор 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Автор 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Автор 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Автор 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Автор 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Автор 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Автор 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Автор 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Автор 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Автор 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Автор 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Автор 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Автор 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Автор 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Автор 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Автор 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Автор 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Автор 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Автор 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Автор 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Автор 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Автор 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Автор 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Автор 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Автор 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Автор 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Автор 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Автор 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Автор 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Автор 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Автор 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Автор 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Автор 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Автор 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Автор 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Автор 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Автор 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Автор 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Автор 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Автор 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Автор 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Автор 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Автор 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Автор 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Автор 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Автор 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Автор 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Автор 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Автор 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Автор 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Автор 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Автор 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Автор 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Автор 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Автор 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Автор 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Автор 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Автор 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Автор 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Автор 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Автор 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Автор 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Автор 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Автор 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Автор 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Автор 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Автор 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Автор 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Автор 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Автор 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Автор 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Автор 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Автор 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Автор 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Автор 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Автор 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Автор 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Автор 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Автор 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Автор 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Автор 100"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Автор 101"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Автор 102"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Автор 103"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Автор 104"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Автор 105"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Автор 106"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Автор 107"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Автор 108"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Автор 109"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Автор 110"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Автор 111"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Автор 112"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Автор 113"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Автор 114"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Автор 115"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Автор 116"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Автор 117"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Автор 118"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Автор 119"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Автор 120"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Автор 121"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Автор 122"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Автор 123"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Автор 124"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Автор 125"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Автор 126"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Автор 127"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Автор 128"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Автор 129"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Автор 130"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Автор 131"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Автор 132"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Автор 133"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Автор 134"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Автор 135"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Автор 136"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Автор 137"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Автор 138"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Автор 139"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Автор 140"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Автор 141"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Автор 142"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Автор 143"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Автор 144"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Автор 145"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Автор 146"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Автор 147"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Автор 148"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Автор 149"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Автор 150"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Автор 151"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Автор 152"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Автор 153"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Автор 154"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Автор 155"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Автор 156"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Автор 157"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Автор 158"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Автор 159"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Автор 160"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Автор 161"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Автор 162"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Автор 163"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Автор 164"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Автор 165"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Автор 166"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Автор 167"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Автор 168"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Автор 169"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Автор 170"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Автор 171"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Автор 172"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Автор 173"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Автор 174"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Автор 175"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Автор 176"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Автор 177"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Автор 178"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Автор 179"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Автор 180"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Автор 181"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Автор 182"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Автор 183"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Автор 184"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Автор 185"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Автор 186"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Автор 187"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Автор 188"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Автор 189"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Автор 190"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Автор 191"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Автор 192"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Автор 193"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Автор 194"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Автор 195"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Автор 196"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Автор 197"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Автор 198"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Автор 199"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Автор 200"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Автор 201"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Автор 202"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Автор 203"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Автор 204"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Автор 205"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Автор 206"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Автор 207"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Автор 208"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Автор 209"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Автор 210"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Автор 211"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Автор 212"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Автор 213"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Автор 214"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Автор 215"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Автор 216"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Автор 217"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Автор 218"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Автор 219"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Автор 220"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Автор 221"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Автор 222"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Автор 223"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Автор 224"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Автор 225"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Автор 226"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Автор 227"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Автор 228"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Автор 229"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Автор 230"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Автор 231"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Автор 232"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Автор 233"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Автор 234"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Автор 235"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Автор 236"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Автор 237"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Автор 238"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Автор 239"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Автор 240"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Автор 241"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Автор 242"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Автор 243"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Автор 244"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Автор 245"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Автор 246"
                        },
                        new
                        {
                            Id = 247,
                            Name = "Автор 247"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Автор 248"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Автор 249"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Автор 250"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Автор 251"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Автор 252"
                        },
                        new
                        {
                            Id = 253,
                            Name = "Автор 253"
                        },
                        new
                        {
                            Id = 254,
                            Name = "Автор 254"
                        },
                        new
                        {
                            Id = 255,
                            Name = "Автор 255"
                        },
                        new
                        {
                            Id = 256,
                            Name = "Автор 256"
                        },
                        new
                        {
                            Id = 257,
                            Name = "Автор 257"
                        },
                        new
                        {
                            Id = 258,
                            Name = "Автор 258"
                        },
                        new
                        {
                            Id = 259,
                            Name = "Автор 259"
                        },
                        new
                        {
                            Id = 260,
                            Name = "Автор 260"
                        },
                        new
                        {
                            Id = 261,
                            Name = "Автор 261"
                        },
                        new
                        {
                            Id = 262,
                            Name = "Автор 262"
                        },
                        new
                        {
                            Id = 263,
                            Name = "Автор 263"
                        },
                        new
                        {
                            Id = 264,
                            Name = "Автор 264"
                        },
                        new
                        {
                            Id = 265,
                            Name = "Автор 265"
                        },
                        new
                        {
                            Id = 266,
                            Name = "Автор 266"
                        },
                        new
                        {
                            Id = 267,
                            Name = "Автор 267"
                        },
                        new
                        {
                            Id = 268,
                            Name = "Автор 268"
                        },
                        new
                        {
                            Id = 269,
                            Name = "Автор 269"
                        },
                        new
                        {
                            Id = 270,
                            Name = "Автор 270"
                        },
                        new
                        {
                            Id = 271,
                            Name = "Автор 271"
                        },
                        new
                        {
                            Id = 272,
                            Name = "Автор 272"
                        },
                        new
                        {
                            Id = 273,
                            Name = "Автор 273"
                        },
                        new
                        {
                            Id = 274,
                            Name = "Автор 274"
                        },
                        new
                        {
                            Id = 275,
                            Name = "Автор 275"
                        },
                        new
                        {
                            Id = 276,
                            Name = "Автор 276"
                        },
                        new
                        {
                            Id = 277,
                            Name = "Автор 277"
                        },
                        new
                        {
                            Id = 278,
                            Name = "Автор 278"
                        },
                        new
                        {
                            Id = 279,
                            Name = "Автор 279"
                        },
                        new
                        {
                            Id = 280,
                            Name = "Автор 280"
                        },
                        new
                        {
                            Id = 281,
                            Name = "Автор 281"
                        },
                        new
                        {
                            Id = 282,
                            Name = "Автор 282"
                        },
                        new
                        {
                            Id = 283,
                            Name = "Автор 283"
                        },
                        new
                        {
                            Id = 284,
                            Name = "Автор 284"
                        },
                        new
                        {
                            Id = 285,
                            Name = "Автор 285"
                        },
                        new
                        {
                            Id = 286,
                            Name = "Автор 286"
                        },
                        new
                        {
                            Id = 287,
                            Name = "Автор 287"
                        },
                        new
                        {
                            Id = 288,
                            Name = "Автор 288"
                        },
                        new
                        {
                            Id = 289,
                            Name = "Автор 289"
                        },
                        new
                        {
                            Id = 290,
                            Name = "Автор 290"
                        },
                        new
                        {
                            Id = 291,
                            Name = "Автор 291"
                        },
                        new
                        {
                            Id = 292,
                            Name = "Автор 292"
                        },
                        new
                        {
                            Id = 293,
                            Name = "Автор 293"
                        },
                        new
                        {
                            Id = 294,
                            Name = "Автор 294"
                        },
                        new
                        {
                            Id = 295,
                            Name = "Автор 295"
                        },
                        new
                        {
                            Id = 296,
                            Name = "Автор 296"
                        },
                        new
                        {
                            Id = 297,
                            Name = "Автор 297"
                        },
                        new
                        {
                            Id = 298,
                            Name = "Автор 298"
                        },
                        new
                        {
                            Id = 299,
                            Name = "Автор 299"
                        },
                        new
                        {
                            Id = 300,
                            Name = "Автор 300"
                        },
                        new
                        {
                            Id = 301,
                            Name = "Автор 301"
                        },
                        new
                        {
                            Id = 302,
                            Name = "Автор 302"
                        },
                        new
                        {
                            Id = 303,
                            Name = "Автор 303"
                        },
                        new
                        {
                            Id = 304,
                            Name = "Автор 304"
                        },
                        new
                        {
                            Id = 305,
                            Name = "Автор 305"
                        },
                        new
                        {
                            Id = 306,
                            Name = "Автор 306"
                        },
                        new
                        {
                            Id = 307,
                            Name = "Автор 307"
                        },
                        new
                        {
                            Id = 308,
                            Name = "Автор 308"
                        },
                        new
                        {
                            Id = 309,
                            Name = "Автор 309"
                        },
                        new
                        {
                            Id = 310,
                            Name = "Автор 310"
                        },
                        new
                        {
                            Id = 311,
                            Name = "Автор 311"
                        },
                        new
                        {
                            Id = 312,
                            Name = "Автор 312"
                        },
                        new
                        {
                            Id = 313,
                            Name = "Автор 313"
                        },
                        new
                        {
                            Id = 314,
                            Name = "Автор 314"
                        },
                        new
                        {
                            Id = 315,
                            Name = "Автор 315"
                        },
                        new
                        {
                            Id = 316,
                            Name = "Автор 316"
                        },
                        new
                        {
                            Id = 317,
                            Name = "Автор 317"
                        },
                        new
                        {
                            Id = 318,
                            Name = "Автор 318"
                        },
                        new
                        {
                            Id = 319,
                            Name = "Автор 319"
                        },
                        new
                        {
                            Id = 320,
                            Name = "Автор 320"
                        },
                        new
                        {
                            Id = 321,
                            Name = "Автор 321"
                        },
                        new
                        {
                            Id = 322,
                            Name = "Автор 322"
                        },
                        new
                        {
                            Id = 323,
                            Name = "Автор 323"
                        },
                        new
                        {
                            Id = 324,
                            Name = "Автор 324"
                        },
                        new
                        {
                            Id = 325,
                            Name = "Автор 325"
                        },
                        new
                        {
                            Id = 326,
                            Name = "Автор 326"
                        },
                        new
                        {
                            Id = 327,
                            Name = "Автор 327"
                        },
                        new
                        {
                            Id = 328,
                            Name = "Автор 328"
                        },
                        new
                        {
                            Id = 329,
                            Name = "Автор 329"
                        },
                        new
                        {
                            Id = 330,
                            Name = "Автор 330"
                        },
                        new
                        {
                            Id = 331,
                            Name = "Автор 331"
                        },
                        new
                        {
                            Id = 332,
                            Name = "Автор 332"
                        },
                        new
                        {
                            Id = 333,
                            Name = "Автор 333"
                        },
                        new
                        {
                            Id = 334,
                            Name = "Автор 334"
                        },
                        new
                        {
                            Id = 335,
                            Name = "Автор 335"
                        },
                        new
                        {
                            Id = 336,
                            Name = "Автор 336"
                        },
                        new
                        {
                            Id = 337,
                            Name = "Автор 337"
                        },
                        new
                        {
                            Id = 338,
                            Name = "Автор 338"
                        },
                        new
                        {
                            Id = 339,
                            Name = "Автор 339"
                        },
                        new
                        {
                            Id = 340,
                            Name = "Автор 340"
                        },
                        new
                        {
                            Id = 341,
                            Name = "Автор 341"
                        },
                        new
                        {
                            Id = 342,
                            Name = "Автор 342"
                        },
                        new
                        {
                            Id = 343,
                            Name = "Автор 343"
                        },
                        new
                        {
                            Id = 344,
                            Name = "Автор 344"
                        },
                        new
                        {
                            Id = 345,
                            Name = "Автор 345"
                        },
                        new
                        {
                            Id = 346,
                            Name = "Автор 346"
                        },
                        new
                        {
                            Id = 347,
                            Name = "Автор 347"
                        },
                        new
                        {
                            Id = 348,
                            Name = "Автор 348"
                        },
                        new
                        {
                            Id = 349,
                            Name = "Автор 349"
                        },
                        new
                        {
                            Id = 350,
                            Name = "Автор 350"
                        },
                        new
                        {
                            Id = 351,
                            Name = "Автор 351"
                        },
                        new
                        {
                            Id = 352,
                            Name = "Автор 352"
                        },
                        new
                        {
                            Id = 353,
                            Name = "Автор 353"
                        },
                        new
                        {
                            Id = 354,
                            Name = "Автор 354"
                        },
                        new
                        {
                            Id = 355,
                            Name = "Автор 355"
                        },
                        new
                        {
                            Id = 356,
                            Name = "Автор 356"
                        },
                        new
                        {
                            Id = 357,
                            Name = "Автор 357"
                        },
                        new
                        {
                            Id = 358,
                            Name = "Автор 358"
                        },
                        new
                        {
                            Id = 359,
                            Name = "Автор 359"
                        },
                        new
                        {
                            Id = 360,
                            Name = "Автор 360"
                        },
                        new
                        {
                            Id = 361,
                            Name = "Автор 361"
                        },
                        new
                        {
                            Id = 362,
                            Name = "Автор 362"
                        },
                        new
                        {
                            Id = 363,
                            Name = "Автор 363"
                        },
                        new
                        {
                            Id = 364,
                            Name = "Автор 364"
                        },
                        new
                        {
                            Id = 365,
                            Name = "Автор 365"
                        },
                        new
                        {
                            Id = 366,
                            Name = "Автор 366"
                        },
                        new
                        {
                            Id = 367,
                            Name = "Автор 367"
                        },
                        new
                        {
                            Id = 368,
                            Name = "Автор 368"
                        },
                        new
                        {
                            Id = 369,
                            Name = "Автор 369"
                        },
                        new
                        {
                            Id = 370,
                            Name = "Автор 370"
                        },
                        new
                        {
                            Id = 371,
                            Name = "Автор 371"
                        },
                        new
                        {
                            Id = 372,
                            Name = "Автор 372"
                        },
                        new
                        {
                            Id = 373,
                            Name = "Автор 373"
                        },
                        new
                        {
                            Id = 374,
                            Name = "Автор 374"
                        },
                        new
                        {
                            Id = 375,
                            Name = "Автор 375"
                        },
                        new
                        {
                            Id = 376,
                            Name = "Автор 376"
                        },
                        new
                        {
                            Id = 377,
                            Name = "Автор 377"
                        },
                        new
                        {
                            Id = 378,
                            Name = "Автор 378"
                        },
                        new
                        {
                            Id = 379,
                            Name = "Автор 379"
                        },
                        new
                        {
                            Id = 380,
                            Name = "Автор 380"
                        },
                        new
                        {
                            Id = 381,
                            Name = "Автор 381"
                        },
                        new
                        {
                            Id = 382,
                            Name = "Автор 382"
                        },
                        new
                        {
                            Id = 383,
                            Name = "Автор 383"
                        },
                        new
                        {
                            Id = 384,
                            Name = "Автор 384"
                        },
                        new
                        {
                            Id = 385,
                            Name = "Автор 385"
                        },
                        new
                        {
                            Id = 386,
                            Name = "Автор 386"
                        },
                        new
                        {
                            Id = 387,
                            Name = "Автор 387"
                        },
                        new
                        {
                            Id = 388,
                            Name = "Автор 388"
                        },
                        new
                        {
                            Id = 389,
                            Name = "Автор 389"
                        },
                        new
                        {
                            Id = 390,
                            Name = "Автор 390"
                        },
                        new
                        {
                            Id = 391,
                            Name = "Автор 391"
                        },
                        new
                        {
                            Id = 392,
                            Name = "Автор 392"
                        },
                        new
                        {
                            Id = 393,
                            Name = "Автор 393"
                        },
                        new
                        {
                            Id = 394,
                            Name = "Автор 394"
                        },
                        new
                        {
                            Id = 395,
                            Name = "Автор 395"
                        },
                        new
                        {
                            Id = 396,
                            Name = "Автор 396"
                        },
                        new
                        {
                            Id = 397,
                            Name = "Автор 397"
                        },
                        new
                        {
                            Id = 398,
                            Name = "Автор 398"
                        },
                        new
                        {
                            Id = 399,
                            Name = "Автор 399"
                        },
                        new
                        {
                            Id = 400,
                            Name = "Автор 400"
                        },
                        new
                        {
                            Id = 401,
                            Name = "Автор 401"
                        },
                        new
                        {
                            Id = 402,
                            Name = "Автор 402"
                        },
                        new
                        {
                            Id = 403,
                            Name = "Автор 403"
                        },
                        new
                        {
                            Id = 404,
                            Name = "Автор 404"
                        },
                        new
                        {
                            Id = 405,
                            Name = "Автор 405"
                        },
                        new
                        {
                            Id = 406,
                            Name = "Автор 406"
                        },
                        new
                        {
                            Id = 407,
                            Name = "Автор 407"
                        },
                        new
                        {
                            Id = 408,
                            Name = "Автор 408"
                        },
                        new
                        {
                            Id = 409,
                            Name = "Автор 409"
                        },
                        new
                        {
                            Id = 410,
                            Name = "Автор 410"
                        },
                        new
                        {
                            Id = 411,
                            Name = "Автор 411"
                        },
                        new
                        {
                            Id = 412,
                            Name = "Автор 412"
                        },
                        new
                        {
                            Id = 413,
                            Name = "Автор 413"
                        },
                        new
                        {
                            Id = 414,
                            Name = "Автор 414"
                        },
                        new
                        {
                            Id = 415,
                            Name = "Автор 415"
                        },
                        new
                        {
                            Id = 416,
                            Name = "Автор 416"
                        },
                        new
                        {
                            Id = 417,
                            Name = "Автор 417"
                        },
                        new
                        {
                            Id = 418,
                            Name = "Автор 418"
                        },
                        new
                        {
                            Id = 419,
                            Name = "Автор 419"
                        },
                        new
                        {
                            Id = 420,
                            Name = "Автор 420"
                        },
                        new
                        {
                            Id = 421,
                            Name = "Автор 421"
                        },
                        new
                        {
                            Id = 422,
                            Name = "Автор 422"
                        },
                        new
                        {
                            Id = 423,
                            Name = "Автор 423"
                        },
                        new
                        {
                            Id = 424,
                            Name = "Автор 424"
                        },
                        new
                        {
                            Id = 425,
                            Name = "Автор 425"
                        },
                        new
                        {
                            Id = 426,
                            Name = "Автор 426"
                        },
                        new
                        {
                            Id = 427,
                            Name = "Автор 427"
                        },
                        new
                        {
                            Id = 428,
                            Name = "Автор 428"
                        },
                        new
                        {
                            Id = 429,
                            Name = "Автор 429"
                        },
                        new
                        {
                            Id = 430,
                            Name = "Автор 430"
                        },
                        new
                        {
                            Id = 431,
                            Name = "Автор 431"
                        },
                        new
                        {
                            Id = 432,
                            Name = "Автор 432"
                        },
                        new
                        {
                            Id = 433,
                            Name = "Автор 433"
                        },
                        new
                        {
                            Id = 434,
                            Name = "Автор 434"
                        },
                        new
                        {
                            Id = 435,
                            Name = "Автор 435"
                        },
                        new
                        {
                            Id = 436,
                            Name = "Автор 436"
                        },
                        new
                        {
                            Id = 437,
                            Name = "Автор 437"
                        },
                        new
                        {
                            Id = 438,
                            Name = "Автор 438"
                        },
                        new
                        {
                            Id = 439,
                            Name = "Автор 439"
                        },
                        new
                        {
                            Id = 440,
                            Name = "Автор 440"
                        },
                        new
                        {
                            Id = 441,
                            Name = "Автор 441"
                        },
                        new
                        {
                            Id = 442,
                            Name = "Автор 442"
                        },
                        new
                        {
                            Id = 443,
                            Name = "Автор 443"
                        },
                        new
                        {
                            Id = 444,
                            Name = "Автор 444"
                        },
                        new
                        {
                            Id = 445,
                            Name = "Автор 445"
                        },
                        new
                        {
                            Id = 446,
                            Name = "Автор 446"
                        },
                        new
                        {
                            Id = 447,
                            Name = "Автор 447"
                        },
                        new
                        {
                            Id = 448,
                            Name = "Автор 448"
                        },
                        new
                        {
                            Id = 449,
                            Name = "Автор 449"
                        },
                        new
                        {
                            Id = 450,
                            Name = "Автор 450"
                        },
                        new
                        {
                            Id = 451,
                            Name = "Автор 451"
                        },
                        new
                        {
                            Id = 452,
                            Name = "Автор 452"
                        },
                        new
                        {
                            Id = 453,
                            Name = "Автор 453"
                        },
                        new
                        {
                            Id = 454,
                            Name = "Автор 454"
                        },
                        new
                        {
                            Id = 455,
                            Name = "Автор 455"
                        },
                        new
                        {
                            Id = 456,
                            Name = "Автор 456"
                        },
                        new
                        {
                            Id = 457,
                            Name = "Автор 457"
                        },
                        new
                        {
                            Id = 458,
                            Name = "Автор 458"
                        },
                        new
                        {
                            Id = 459,
                            Name = "Автор 459"
                        },
                        new
                        {
                            Id = 460,
                            Name = "Автор 460"
                        },
                        new
                        {
                            Id = 461,
                            Name = "Автор 461"
                        },
                        new
                        {
                            Id = 462,
                            Name = "Автор 462"
                        },
                        new
                        {
                            Id = 463,
                            Name = "Автор 463"
                        },
                        new
                        {
                            Id = 464,
                            Name = "Автор 464"
                        },
                        new
                        {
                            Id = 465,
                            Name = "Автор 465"
                        },
                        new
                        {
                            Id = 466,
                            Name = "Автор 466"
                        },
                        new
                        {
                            Id = 467,
                            Name = "Автор 467"
                        },
                        new
                        {
                            Id = 468,
                            Name = "Автор 468"
                        },
                        new
                        {
                            Id = 469,
                            Name = "Автор 469"
                        },
                        new
                        {
                            Id = 470,
                            Name = "Автор 470"
                        },
                        new
                        {
                            Id = 471,
                            Name = "Автор 471"
                        },
                        new
                        {
                            Id = 472,
                            Name = "Автор 472"
                        },
                        new
                        {
                            Id = 473,
                            Name = "Автор 473"
                        },
                        new
                        {
                            Id = 474,
                            Name = "Автор 474"
                        },
                        new
                        {
                            Id = 475,
                            Name = "Автор 475"
                        },
                        new
                        {
                            Id = 476,
                            Name = "Автор 476"
                        },
                        new
                        {
                            Id = 477,
                            Name = "Автор 477"
                        },
                        new
                        {
                            Id = 478,
                            Name = "Автор 478"
                        },
                        new
                        {
                            Id = 479,
                            Name = "Автор 479"
                        },
                        new
                        {
                            Id = 480,
                            Name = "Автор 480"
                        },
                        new
                        {
                            Id = 481,
                            Name = "Автор 481"
                        },
                        new
                        {
                            Id = 482,
                            Name = "Автор 482"
                        },
                        new
                        {
                            Id = 483,
                            Name = "Автор 483"
                        },
                        new
                        {
                            Id = 484,
                            Name = "Автор 484"
                        },
                        new
                        {
                            Id = 485,
                            Name = "Автор 485"
                        },
                        new
                        {
                            Id = 486,
                            Name = "Автор 486"
                        },
                        new
                        {
                            Id = 487,
                            Name = "Автор 487"
                        },
                        new
                        {
                            Id = 488,
                            Name = "Автор 488"
                        },
                        new
                        {
                            Id = 489,
                            Name = "Автор 489"
                        },
                        new
                        {
                            Id = 490,
                            Name = "Автор 490"
                        },
                        new
                        {
                            Id = 491,
                            Name = "Автор 491"
                        },
                        new
                        {
                            Id = 492,
                            Name = "Автор 492"
                        },
                        new
                        {
                            Id = 493,
                            Name = "Автор 493"
                        },
                        new
                        {
                            Id = 494,
                            Name = "Автор 494"
                        },
                        new
                        {
                            Id = 495,
                            Name = "Автор 495"
                        },
                        new
                        {
                            Id = 496,
                            Name = "Автор 496"
                        },
                        new
                        {
                            Id = 497,
                            Name = "Автор 497"
                        },
                        new
                        {
                            Id = 498,
                            Name = "Автор 498"
                        },
                        new
                        {
                            Id = 499,
                            Name = "Автор 499"
                        },
                        new
                        {
                            Id = 500,
                            Name = "Автор 500"
                        });
                });

            modelBuilder.Entity("BookWebApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", "authors");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Description = "Биографическое описание жизни",
                            ImageUrl = "123",
                            Title = "Первая книга Васи"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Description = "Фантастическая книга о приключениях",
                            ImageUrl = "123",
                            Title = "Вторая книга Васи"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Description = "Историческая книга",
                            ImageUrl = "123",
                            Title = "Третья книга Васи"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Description = "Фентази об эльфах",
                            ImageUrl = "123",
                            Title = "Первая книга Пети"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Description = "Научная литература, докозательство 3-й теорему Фихтенгольца",
                            ImageUrl = "123",
                            Title = "Вторая книга Пети"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Description = "Научная фантастика и приключение героя в далёком космосе",
                            ImageUrl = "123",
                            Title = "Третья книга Пети"
                        });
                });

            modelBuilder.Entity("BookWebApp.Models.BookDetails", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Editor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<decimal>("HardcoverCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Illustrator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PaperbackCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rank")
                        .HasColumnType("float");

                    b.Property<byte>("ReadingAge")
                        .HasColumnType("tinyint");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId");

                    b.ToTable("BookDetails", "authors");

                    b.HasData(
                        new
                        {
                            BookId = 3,
                            Editor = "Не известен",
                            Genre = 4,
                            HardcoverCost = 100m,
                            Illustrator = "МИКЕЛАНДЖЕЛО",
                            Language = 0,
                            PageCount = 100,
                            PaperbackCost = 0m,
                            Rank = 7.1120000000000001,
                            ReadingAge = (byte)18,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 4,
                            Editor = "Не известен",
                            Genre = 0,
                            HardcoverCost = 110m,
                            Illustrator = "ЙОХАННЕС ВЕРМЕЕР",
                            Language = 2,
                            PageCount = 200,
                            PaperbackCost = 0m,
                            Rank = 4.343,
                            ReadingAge = (byte)12,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 5,
                            Editor = "Не известен",
                            Genre = 4,
                            HardcoverCost = 120m,
                            Illustrator = "ПАБЛО ПИКАССО",
                            Language = 0,
                            PageCount = 300,
                            PaperbackCost = 0m,
                            Rank = 9.1999999999999993,
                            ReadingAge = (byte)10,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 6,
                            Editor = "Не известен",
                            Genre = 1,
                            HardcoverCost = 130m,
                            Illustrator = "ВИНСЕНТ ВАН ГОГ",
                            Language = 2,
                            PageCount = 400,
                            PaperbackCost = 0m,
                            Rank = 8.3450000000000006,
                            ReadingAge = (byte)5,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 7,
                            Editor = "Не известен",
                            Genre = 3,
                            HardcoverCost = 140m,
                            Illustrator = "РЕМБРАНДТ ВАН РЕЙН",
                            Language = 1,
                            PageCount = 500,
                            PaperbackCost = 0m,
                            Rank = 1.0,
                            ReadingAge = (byte)10,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 8,
                            Editor = "Не известен",
                            Genre = 0,
                            HardcoverCost = 150m,
                            Illustrator = "ЛЕОНАРДО ДА ВИНЧИ",
                            Language = 2,
                            PageCount = 600,
                            PaperbackCost = 0m,
                            Rank = 5.0,
                            ReadingAge = (byte)18,
                            Reviews = 0,
                            Status = 0,
                            Year = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookWebApp.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers", "authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Издательство ООО \"Beautiful\""
                        },
                        new
                        {
                            Id = 2,
                            Name = "Издательство ООО \"Summer\""
                        });
                });

            modelBuilder.Entity("BookWebApp.Models.PublishersAuthors", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.ToTable("PublishersAuthors", "authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            PublisherId = 1
                        },
                        new
                        {
                            AuthorId = 2,
                            PublisherId = 1
                        },
                        new
                        {
                            AuthorId = 1,
                            PublisherId = 2
                        });
                });

            modelBuilder.Entity("BookWebApp.Models.Book", b =>
                {
                    b.HasOne("BookWebApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookWebApp.Models.BookDetails", b =>
                {
                    b.HasOne("BookWebApp.Models.Book", "Book")
                        .WithOne("Details")
                        .HasForeignKey("BookWebApp.Models.BookDetails", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookWebApp.Models.PublishersAuthors", b =>
                {
                    b.HasOne("BookWebApp.Models.Author", "Author")
                        .WithMany("PublishersAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookWebApp.Models.Publisher", "Publisher")
                        .WithMany("PublishersAuthors")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookWebApp.Models.Author", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("PublishersAuthors");
                });

            modelBuilder.Entity("BookWebApp.Models.Book", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("BookWebApp.Models.Publisher", b =>
                {
                    b.Navigation("PublishersAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
